<?php

// WhatsApp Cloud API (Meta) and the services that read the commands. Secrets come only from the
// environment (deploy/.env on the server); the admin turns the feature on in the panel.
return [
    // QR-linked phone through the WAHA service (deploy/docker-compose.yml). The service only listens
    // inside the server's private network; its key and the webhook secret are generated by update.sh.
    'waha' => [
        'url' => env('WAHA_URL', 'http://waha:3000'),
        'api_key' => env('WAHA_API_KEY'),
        'session' => env('WAHA_SESSION', 'default'),
        'webhook_secret' => env('WAHA_WEBHOOK_SECRET'),
        'webhook_url' => env('WAHA_WEBHOOK_URL', 'http://app:8080/whatsapp/qr-webhook'),
    ],

    // Seconds between two messages sent from the linked phone (random within the range), to look human.
    'send_delay' => [(int) env('WHATSAPP_SEND_DELAY_MIN', 3), (int) env('WHATSAPP_SEND_DELAY_MAX', 8)],

    // Meta WhatsApp Cloud API (the other connection type).
    'access_token' => env('WHATSAPP_ACCESS_TOKEN'),
    'phone_number_id' => env('WHATSAPP_PHONE_NUMBER_ID'),
    'app_secret' => env('WHATSAPP_APP_SECRET'),
    'verify_token' => env('WHATSAPP_VERIFY_TOKEN'),
    'graph_version' => env('WHATSAPP_GRAPH_VERSION', 'v23.0'),

    // Understanding free text in Iraqi Arabic (Claude).
    'ai' => [
        'api_key' => env('ANTHROPIC_API_KEY'),
        'model' => env('WHATSAPP_AI_MODEL', 'claude-opus-5-5'),
    ],

    // Voice notes to text: free on our own server (the «whisper» service) unless an OpenAI key is set.
    'transcribe' => [
        'local_url' => env('WHISPER_URL', 'http://whisper:9000'),
        'api_key' => env('WHATSAPP_TRANSCRIBE_API_KEY', env('OPENAI_API_KEY')),
        'url' => env('WHATSAPP_TRANSCRIBE_URL', 'https://api.openai.com/v1/audio/transcriptions'),
        'model' => env('WHATSAPP_TRANSCRIBE_MODEL', 'whisper-1'),
    ],
];
